import "./globals.css";

import { Footer } from "./components/ui/Footer";
import { Header } from "./components/ui/Header";
import { Inter } from "next/font/google";
import type { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full flex-initial bg-[#edeafe]">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
